# Generated by Django 4.1.4 on 2023-08-03 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reg',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('avatarId', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('isEnabled', models.BooleanField(default=True)),
                ('verified', models.BooleanField(default=True)),
                ('bannedUntil', models.DateTimeField(auto_now=True)),
                ('activity', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
