# Generated by Django 4.1.4 on 2023-08-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegAPI', '0002_rename_reg_userfields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfields',
            name='balance',
            field=models.JSONField(default=dict),
        ),
    ]
