# Generated by Django 4.1.4 on 2023-08-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegAPI', '0003_userfields_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkinsFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
